//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongBanVeMayBay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYENBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUYENBAY()
        {
            this.CHI_TIET_LICH_CHUYEN_BAY = new HashSet<CHI_TIET_LICH_CHUYEN_BAY>();
            this.VECHUYENBAYs = new HashSet<VECHUYENBAY>();
        }
    
        public int ID { get; set; }
        public string IDChuyenBay { get; set; }
        public string IDSanBayDi { get; set; }
        public string IDSanBayDen { get; set; }
        public int GiaTien { get; set; }
        public System.DateTime NgayGio { get; set; }
        public System.TimeSpan ThoiGianBay { get; set; }
        public int SoGheHang1 { get; set; }
        public int SoGheHang2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_LICH_CHUYEN_BAY> CHI_TIET_LICH_CHUYEN_BAY { get; set; }
        public virtual SANBAY SANBAY { get; set; }
        public virtual SANBAY SANBAY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VECHUYENBAY> VECHUYENBAYs { get; set; }
    }
}
