//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongBanVeMayBay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            ImageEmp = "~/Content/images/add.jpg";
        }
        public int ID { get; set; }
        [Display(Name = "Mã NV: ")]
        public string IDNhanVien { get; set; }

        [Display(Name = "Tên NV: ")]
        public string TenNV { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        [Display(Name = "Ngày sinh: ")]
        public DateTime NgaySinh { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        [Display(Name = "Ngày vào làm: ")]
        public DateTime NgayVaoLam { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        [Display(Name = "Ngày nghỉ làm: ")]
        public Nullable<DateTime> NgayNghiLam { get; set; }
        [Display(Name = "Chức vụ: ")]
        public string ChucVu { get; set; }

        [Display(Name = "Bộ phận: ")]
        public string BoPhan { get; set; }

        [Display(Name = "Avatar: ")]
        public string ImageEmp { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }

        public virtual CATEGORY CATEGORY { get; set; }
    }
}
